// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBD0H5SUFG6aOU42tlL3UO-6WTPmabMvc',
    appId: '1:137703623300:web:bed0bd92b7cf9d86e010d1',
    messagingSenderId: '137703623300',
    projectId: 'pards1mjane-42048',
    authDomain: 'pards1mjane-42048.firebaseapp.com',
    storageBucket: 'pards1mjane-42048.appspot.com',
    measurementId: 'G-0CN4TGPSDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRz1z7wb8Lqeu8wOxN_f45upDg2vMODc',
    appId: '1:137703623300:android:80fa993f52814547e010d1',
    messagingSenderId: '137703623300',
    projectId: 'pards1mjane-42048',
    storageBucket: 'pards1mjane-42048.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hVB5rjo1ZtKnK8YRVgINSbaYSiOjGLw',
    appId: '1:137703623300:ios:ae366997084277a5e010d1',
    messagingSenderId: '137703623300',
    projectId: 'pards1mjane-42048',
    storageBucket: 'pards1mjane-42048.appspot.com',
    iosClientId: '137703623300-8i596ora78ktp59omdla6gm9keg2o8sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0hVB5rjo1ZtKnK8YRVgINSbaYSiOjGLw',
    appId: '1:137703623300:ios:ae366997084277a5e010d1',
    messagingSenderId: '137703623300',
    projectId: 'pards1mjane-42048',
    storageBucket: 'pards1mjane-42048.appspot.com',
    iosClientId: '137703623300-8i596ora78ktp59omdla6gm9keg2o8sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEx',
  );
}
